### ISSUE TITLE
Training not providing enough matches

### ISSUE THREAD

**Issue by tigerang22** [dedupeio/dedupe#1077]
I have been using dedupe 2.0.6. Recently I ran into the KeyError [issue](https://github.com/dedupeio/dedupe/issues/986) with a dataset of 78,598 records. After I upgraded to version 2.017, the KeyError issue has been resolved. However as I am doing regression testing using 2.0.17 against the previous datasets, I have noticed a dramatic memory increase from 300 mb to 8-10 gb and twice as much time as version 2.06 during the deduper.prepare_training() call on my windows machine for a dataset with 121,420 records (I have a Linux app service in Azure that I had to double the size for. I haven't measured the actual memory consumption yet so can't give the metrics at the moment). The more significant problem is that although there is better sampling according to [this](https://github.com/dedupeio/dedupe/pull/982), my training session consistently ends up with 200-300 distincts and only 3-5 matches. 

@fgregg, is this problem related to sampling solely or have other things been changed since 2.06 that is causing what I am experiencing, i.e. memory, perf and not enough matches during training? I have noticed that the old sampling code, that caused the KeyError, had been moved out of core.py to convenience.py and new sampling code is now being used.

**Comment by fgregg** [comment]
there's been a number of changes that could impact the active labeling.

if you could isolate this to a specific release that would be helpful. 

if you could provide some example data where the current code seems to be performing worse, that would also be very helpful

**Comment by tigerang22** [comment]
@fgregg  thanks for the response. Based on previous comments from @f-hafner, I switched from 2.0.17 back to version 2.0.11, with my own fix to the KeyError issue, the training seems to be well balanced between distincts and matches now. So the issue with not enough matches must have come from 2.0.12 or later. I had this issue when testing with 2.0.17 consistently for three different datasets. At the moment, I can't share the data unfortunately because of PII in there. Interested if anyone has had this issue with any public dataset?

BTW, for those interested, here is my quick fix in core.py in version 2.0.11 for the KeyError when encountered with size of the dataset between ~66,000 and ~92,000:

![image](https://user-images.githubusercontent.com/88054423/184057022-622ea1d3-e1de-433e-8472-8df288cfc484.png)

**Comment by fgregg** [comment]
could you narrow it down to a specific version between 2.11 and 2.17

**Comment by tigerang22** [comment]
Let me do some testing and will let you know...

**Comment by f-hafner** [comment]
I should be able to share a sample of my dataset where the issue occurs; I'll let you know.

**Comment by tigerang22** [comment]
@fgregg It looks that version 2.0.14 introduced the issue, while 2.0.13 is still ok despite the KeyError problem.

@f-hafner can you please try your link use case using 2.0.13 and 2.0.14?

**Comment by fgregg** [comment]
thank you very much!

**Comment by f-hafner** [comment]
@tigerang22 , I think I can confirm this. With 2.0.14, I stopped at 100 negative, 1 positive. With 2.0.13, I stopped at 22 negative, 18 positive. 
I'll prepare the data extract now.

**Comment by f-hafner** [comment]
Here is the repo with data and scripts: https://github.com/f-hafner/dedupe_training_example
I hope it works; let me know if I need to fix something.

**Comment by tigerang22** [comment]
@fgregg any insight on the issue and when a future release would have the fix? Thanks

**Comment by fgregg** [comment]
i believe i have addressed this on main @f-hafner and @tigerang22. can you confirm that it works for your cases?

@f-hafner thank you for the example code, that was very helpful

**Comment by tigerang22** [comment]
@fgregg great! I will give it a try shortly.

**Comment by tigerang22** [comment]
@fgregg I encountered a KeyError related to the datetime field type and it turns out that your commit yesterday doesn't have varibales/date_time.py anymore. Are we expected to add that as a custom type now? Please advise.

**Comment by fgregg** [comment]
ugh! this is probably related to https://github.com/dedupeio/dedupe/issues/1085

**Comment by tigerang22** [comment]
@fgregg I solved the datetime type issue by resetting my virtual environment. Just completed test of commit aa2b04e against my previous dataset. The same problem unfortunately still exists for me, 1 match and close to 100 distinct pairs before I stopped the testing. 

@f-hafner have you had luck with your scenarios?

**Comment by fgregg** [comment]
@tigerang22. that’s unfortunate! i
used to @f-hafner’s example
code to debug. can you provide a reproducible example?

**Comment by f-hafner** [comment]
I haven't tried it out yet, but I will let you know when I have

**Comment by fgregg** [comment]
@f-hafner looks like you installed it okay. it's a bit simpler to do it like this

```bash
pip install https://github.com/dedupeio/dedupe/archive/522e7b2147d61fa36d6dee6288df57aee95c4bcc.zip
```

that's very strange that the performance didn't get better for you. using your test repo, it seemed to be working very well for me. hmmm....

**Comment by johnmarkpittman** [comment]
Is there any chance that this is dependency related? I'm getting similar behavior with my dataset and the above dataset using version 2.0.19

**Comment by fgregg** [comment]
i think i have a fix for this in 2.0.23

**Comment by tigerang22** [comment]
> 

@fgregg Great! I will give 2.0.23 a shot.

**Comment by tigerang22** [comment]
@fgregg I have just tested 2.0.23 and unfortunately the same issue exists. Are there any fine tuning options that might be affecting this, such as calling deduper.prepare_training(temp_d) with dynamic sample_size and blocked_proportion instead of using the default values? I did notice that the previous version such as 2.0.13 would take 4-5 mins but now with 2.0.23 it is taking more than 10 mins to finish the prepare_training call.

**Comment by fgregg** [comment]
@tigerang22 can you check to see if the example that @f-hafner poster also doesn't work for you. (it does for me now).

**Comment by boccheciampe** [comment]
Hello,

I actually struggle with the same problem, version 2.0.23, I've tried to go a little further and stopped at 10 positives and 2000 negatives.

My script is based on the pgsql_big_dedupe_example (hope it's up to date :), adapted to use Django's 3.2 ORM, as I plan to build an identity manager with Dedupe.

My variables are very similar to @f-hafner, I use distinct birth, last, first and middle names (all 'Strings'), a few others (birth date, place, country, ...), and interactions to boost the scores : 

`dedupe_fields = [
    {'field': 'u_birth_name', 'variable name': 'birth_name', 'type': 'String'},
    {'field': 'u_last_name', 'variable name': 'last_name', 'type': 'String', 'has missing': True},
    {'field': 'u_first_name', 'variable name': 'first_name', 'type': 'String'},
    {'field': 'u_second_name', 'variable name': 'second_name', 'type': 'String', 'has missing': True},
    {'field': 'text_birth_date', 'variable name': 'birth_date', 'type': 'ShortString', 'has missing': True},
    {'field': 'u_birth_place', 'variable name': 'birth_place', 'type': 'ShortString', 'has missing': True},

    {'field': 'birth_department_code', 'variable name': 'birth_department_code', 'type': 'Exact', 'has missing': True},
    {'field': 'birth_country_code', 'variable name': 'birth_country_code', 'type': 'Exact', 'has missing': True},
    {'field': 'nationality_code', 'variable name': 'nationality_code', 'type': 'Exact', 'has missing': True},    

    {'type': 'Interaction',
     'interaction variables': ['birth_name', 'first_name', 'birth_date']
    },
]`

It looks like only one field is eventually used as a predicate (in my case, the logger shows it's the birth date, defined either as DateTime or String), and of course it's not enough to efficiently dedupe my 315k entries. Some entities end up with members with only the birth date as common data.

Back to 2.0.13, with the same variables definition, I stopped at 47/10 positive, 1000/10 negative, and the following predicates :
INFO:dedupe.training:Final predicate set:
INFO:dedupe.training:(TfidfNGramCanopyPredicate: (0.6, u_last_name), LevenshteinCanopyPredicate: (1, u_birth_name))
INFO:dedupe.training:(SimplePredicate: (commonTwoTokens, u_birth_name), SimplePredicate: (hundredIntegersOddPredicate, text_birth_date))
INFO:dedupe.training:(SimplePredicate: (firstTwoTokensPredicate, u_first_name), SimplePredicate: (tokenFieldPredicate, u_birth_name))

With this, I end up with ~3000 entities (out of ~28000 I'm supposed to find).

@fgregg since it looks like it works for you, could it come from something I obviously missed in the variables definition ? Is the training engine more efficient with split birth/last/first/... names into multiple variable or to keep these in a single string ? (the question may be valid for other variables too).

Or, since I have quite a lot of entries, does the training simply need a lot more samples, both with 2.0.13 and 2.0.23 ... ?

Thanks for your answers.
